### ISSUE TITLE
Serve files with appropriated MIME type

### ISSUE THREAD

**Issue by Hywan** [fruux/sabre-katana#241]
It will allow browser to show files instead of forcing them to download.

**Comment by evert** [comment]
There's `Sabre\DAV\Browser\GuessContentType`. Probably the best way to implement it.

**Comment by Hywan** [comment]
Heh, yes, but since we have Hoa in sabre/katana, we can use [`Hoa\Mime`](http://hoa-project.net/Literature/Hack/Mime.html) ;-). Much more MIME types supported (even from the system).

**Comment by evert** [comment]
That would work, but I would highly recommend doing it whitelist based. You really don't want to ever serve text/html for example. Very dangerous.

**Comment by evert** [comment]
But it's easy to create your own Hoa\Mime based plugin

**Comment by Hywan** [comment]
Why? It's not :-/.

**Comment by Hywan** [comment]
(about HTML)

**Comment by evert** [comment]
XSS and CSRF

**Comment by Hywan** [comment]
Well, we could use our own MIME type file.

**Comment by evert** [comment]
Not fully sure what you mean with that... the issue is still that if any user is able to write html, it's possible for that user to act on behalf of other users, because they are on the same domain. The only correct way to solve it is to have a separate public domainname, so it's not part of the same browser sandbox.

**Comment by evert** [comment]
Never mind I understand =)
